dynamic-version: attempt to compensate for broken versions of git

diff --git a/_dynamic_version b/_dynamic_version
--- a/_dynamic_version
+++ b/_dynamic_version
@@ -12,6 +12,7 @@ INFILE=configure.ac
 OUTFILE=_dynamic_version.h
 TMPFILE=/tmp/_dyn_version_tmp.h
 TOUCHFILE=version.h
+MIN_GIT_VERSION="1.8"   # (earlier versions of git return inaccurate results)
 
 #------------------------------------------------------------------------------
 #                         create_dyn_vers_hdr
@@ -78,6 +79,94 @@ END_OF_HEADER
   fi
 }
 
+#-----------------------------------------------------------
+#              vercomp  --  compare versions
+#-----------------------------------------------------------
+#
+#   $1:  first version to be compared   (e.g. "1.2.3")
+#   $2:  expected relationship          (e.g. ">")
+#   $3:  second version to be compared  (e.g. "1.2")
+#
+# The algorithm takes into account leading zeros as well
+# as missing components (4.08 < 4.08.01, 3.2.0.9 > 3.2)
+# but only exact equality is supported for for strings
+# which have non-numeric components (1.2rc3 = 1.2rc3).
+#
+# Returns:  0 = success  if relationship is true.
+# Returns:  1 = failure  if relationship is false
+#
+# We use 0 for true and 1 for false so that the caller
+# can do such things as:
+#
+#     if vercomp 1.2.3 '>' 1.2.0; then
+#       echo "True!"
+#     else
+#       echo "FALSE!"
+#     fi
+#
+#-----------------------------------------------------------
+
+vercomp()
+{
+  local op
+
+  _vercomp $1 $3
+
+  case $? in
+      0) op='=';;
+      1) op='>';;
+      2) op='<';;
+  esac
+
+  if [[ $op != $2 ]]; then
+    return 1
+  else
+    return 0
+  fi
+}
+
+#-----------------------------------------------------------
+#              (vercomp helper function)
+#-----------------------------------------------------------
+_vercomp()
+{
+  #  rc = 0:    $1 = $2    $1  equals        $2
+  #  rc = 1:    $1 > $2    $1  greater than  $2
+  #  rc = 2:    $1 < $2    $1  less than     $2
+
+  if [[ $1 == $2 ]]; then
+    return 0
+  fi
+
+  local IFS=.
+  local i ver1=($1) ver2=($2)
+
+  # Fill empty fields in ver1 with zeros
+
+  for ((i=${#ver1[@]}; i<${#ver2[@]}; i++)); do
+    ver1[i]=0
+  done
+
+  for ((i=0; i<${#ver1[@]}; i++)); do
+
+    if [[ -z ${ver2[i]} ]]; then
+      # Fill empty fields in ver2 with zeros
+      ver2[i]=0
+    fi
+
+    if ((10#${ver1[i]} > 10#${ver2[i]})); then
+      return 1
+    fi
+
+    if ((10#${ver1[i]} < 10#${ver2[i]})); then
+      return 2
+    fi
+
+  done
+
+  return 0
+}
+
 #------------------------------------------------------------------------------
 #                             M A I N
 #------------------------------------------------------------------------------
@@ -118,7 +207,7 @@ else
 
   # Determine if any local modifications exist. PLEASE NOTE that doing
   # "update-index --refresh" beforehand is seemingly critical to ensure
-  # accurate "diff-index" results.
+  # accurate "diff-index" results with some versions of git.
 
   git update-index --refresh -q > /dev/null 2>&1
   git diff-index --quiet HEAD
@@ -126,7 +215,13 @@ else
   if test "$?" == "0"; then
     modified_str=""
   else
-    modified_str="-modified"
+    # Check for possibly inaccurate results
+    gitvers=$(git --version | egrep -o "([0-9]{1,}\.)+[0-9]{1,}")
+    if vercomp $gitvers '>' $MIN_GIT_VERSION; then
+      modified_str="-modified"
+    else
+      modified_str="-modified(?)"   # (indicate questionable results)
+    fi
   fi
 
   # Extract the short git hash of the repository (usually the last commit)
