Update DoConfigure to ensure that SoftFloat-3a is installed and ready before configuring Hyperion.
If it is not installed, SoftFloat is cloned in the same way that Hyperion was.
It is then configured and built using the default options.

Then we we run autogen.sh if there is no 'configure'; generate the object
directory structure (SoftFloat has done some of the groundwork here); and
configure using the arguments specified.

diff --git a/DoConfigure b/DoConfigure
--- a/DoConfigure
+++ b/DoConfigure
@@ -6,6 +6,91 @@
 # Your current working directory MUST be the one where this file resides
 # DO NOT source this script.
 
+where=$PWD
+gitconf=.git/config
+sfdir=SoftFloat-3a
+build=../$(uname -m)/hyperion
+obj=../$(uname -m)/s3fh
+
+# Look for SoftFloat; clone if not present; build it if it isn't
+
+# Decode the git configure url statement
+
+testurl () {
+if [ $1 != url ] || [ $2 != "=" ] ; then
+        echo "Git configuration for url not in proper format." >&2
+        echo "Want 'url' have '$1'; want '=' have '$2'."
+        return 14
+fi
+
+pfx=$(echo $3|"cut" -d . -f 1)
+
+case "$pfx" in
+        git@github)
+                clone=git@github.com:hercules-390/$sfdir.git
+                ;;
+        https://github)
+                clone=https://github.com/hercules-390/$sfdir.git
+                ;;
+        *)
+                echo "Git url '$3' does not seem to be correct format." >&2
+                echo "It should start 'git@github' or 'https://github'."
+                return 15
+                ;;
+esac
+
+(cd .. && git clone $clone)
+rv=$?
+
+if [ $rv -ne 0 ] ; then
+        echo "git clone of $sfdir failed rv=$rv."
+        return 16
+fi
+
+return 0
+}
+
+# Try to determine how Hyperion was cloned so that SoftFloat
+# can be cloned the same way.
+
+testSoftFloat () {
+
+if [ -d ../$sfdir ] ; then
+        echo "sfdir is installed." >&2
+else
+        # Need to download and install softfloat.  Try to determine how
+        # Hyperion was cloned and then use same method
+        if [ ! -d .git ] || [ ! -f $gitconf ] ; then
+                echo "Hyperion git configuration file '$gitconf' not found." >&2
+                return 12
+        fi
+
+        remote=$("sed" -n -e '/\[remote/,/\[/p' $gitconf | "grep" 'url *=')
+
+        if [ -z "$remote" ] ; then
+                echo "Cannot determine how Hyperion was cloned." >&2
+                return 13
+        fi
+
+        testurl $remote
+        rv=$?
+
+        if [ 0 -ne $rv ] ; then return $rv ; fi
+fi
+
+if [ -f $obj/include/softfloat.h ] ; then return 0 ; fi
+
+(cd ../$sfdir && ./1Stop)
+rv=$?
+
+if [ 0 -ne $rv ] ; then
+        echo "Could not build $sfdir rv=$rv."
+        return 17
+fi
+
+return 0
+}
+
 dodir () {
 if [ ! -d $1 ] ; then
         mkdir $1
@@ -20,10 +105,20 @@ else
 fi
 }
 
-where=$PWD
-build=../$(uname -m)/hyperion
+testSoftFloat
+rv=$?
+if [ 0 -ne $rv ] ; then exit $rv ; fi
+
+echo "$sfdir installed and built."
+
 dodir ../$(uname -m)
 dodir $build
+
+if [ ! -x configure ] ; then
+        ./autogen.sh
+        rv=$?
+        if [ $rv -ne 0 ] ; then exit 18; fi
+fi
 
 cd $build
 $where/configure "$@"
